### ISSUE TITLE
Compilation problem with today's master

### ISSUE THREAD

**Issue by RubenGarcia** [Stratoscale/swagger#36]
after git clone:
$ cd swagger
$ make
rm -rf example/restapi example/models example/client
docker build . -t go-swagger:strato
Sending build context to Docker daemon    341kB
Step 1/5 : FROM quay.io/goswagger/swagger:v0.17.0
 ---> 1541142c8ca6
Step 2/5 : ADD ./templates /templates
 ---> Using cache
 ---> 448bee5d0257
Step 3/5 : ADD ./entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> f8ee4c4b9516
Step 4/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 345b83a12e4d
Step 5/5 : CMD ["--help"]
 ---> Using cache
 ---> 28556ba6596a
Successfully built 28556ba6596a
Successfully tagged go-swagger:strato
cd example ; \
	docker run --rm -e GOPATH=/home/rgarcia/gocode:/go -v /home/rgarcia/lrz/lexis/wp8/swagger:/home/rgarcia/lrz/lexis/wp8/swagger -w /home/rgarcia/lrz/lexis/wp8/swagger/example -u 1000:1000 go-swagger:strato generate server ; \
	docker run --rm -e GOPATH=/home/rgarcia/gocode:/go -v /home/rgarcia/lrz/lexis/wp8/swagger:/home/rgarcia/lrz/lexis/wp8/swagger -w /home/rgarcia/lrz/lexis/wp8/swagger/example -u 1000:1000 go-swagger:strato generate client ; \
	go generate ./...
2020/03/24 11:13:16 validating spec /home/rgarcia/lrz/lexis/wp8/swagger/example/swagger.yaml
2020/03/24 11:13:17 preprocessing spec with option:  minimal flattening
2020/03/24 11:13:17 building a plan for generation
2020/03/24 11:13:17 lstat /home/rgarcia/gocode: no such file or directory
2020/03/24 11:13:18 validating spec /home/rgarcia/lrz/lexis/wp8/swagger/example/swagger.yaml
2020/03/24 11:13:20 preprocessing spec with option:  minimal flattening
2020/03/24 11:13:20 building a plan for generation
2020/03/24 11:13:20 lstat /home/rgarcia/gocode: no such file or directory
go build ./example/main.go
example/main.go:8:2: use of internal package not allowed
example/main.go:9:2: use of internal package not allowed
../../../../gocode/src/github.com/Stratoscale/swagger/example/internal/pet/pet.go:7:2: cannot find package "github.com/Stratoscale/swagger/example/models" in any of:
	/usr/lib/go-1.10/src/github.com/Stratoscale/swagger/example/models (from $GOROOT)
	/home/rgarcia/gocode/src/github.com/Stratoscale/swagger/example/models (from $GOPATH)
../../../../gocode/src/github.com/Stratoscale/swagger/example/auth/auth.go:9:2: cannot find package "github.com/Stratoscale/swagger/example/restapi" in any of:
	/usr/lib/go-1.10/src/github.com/Stratoscale/swagger/example/restapi (from $GOROOT)
	/home/rgarcia/gocode/src/github.com/Stratoscale/swagger/example/restapi (from $GOPATH)
../../../../gocode/src/github.com/Stratoscale/swagger/example/internal/pet/pet.go:8:2: cannot find package "github.com/Stratoscale/swagger/example/restapi/operations/pet" in any of:
	/usr/lib/go-1.10/src/github.com/Stratoscale/swagger/example/restapi/operations/pet (from $GOROOT)
	/home/rgarcia/gocode/src/github.com/Stratoscale/swagger/example/restapi/operations/pet (from $GOPATH)
../../../../gocode/src/github.com/Stratoscale/swagger/example/internal/store/store.go:6:2: cannot find package "github.com/Stratoscale/swagger/example/restapi/operations/store" in any of:
	/usr/lib/go-1.10/src/github.com/Stratoscale/swagger/example/restapi/operations/store (from $GOROOT)
	/home/rgarcia/gocode/src/github.com/Stratoscale/swagger/example/restapi/operations/store (from $GOPATH)
Makefile:16: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by RubenGarcia** [comment]
Today's master
```
git pull
go get -u -f ./...
make clean
make
...
client/pet/pet_client.go:16: running "mockery": exec: "mockery": executable file not found in $PATH
client/store/store_client.go:16: running "mockery": exec: "mockery": executable file not found in $PATH
restapi/configure_swagger_simple_petstore.go:28: running "mockery": exec: "mockery": executable file not found in $PATH
Makefile:20: recipe for target 'example' failed
make: *** [example] Error 1
```
Where can I obtain the mockery executable? Google did not help and it's not in the ubuntu repository.

**Comment by RubenGarcia** [comment]
Since this repository is abandoned, I am closing this issue.

**Comment by posener** [comment]
@RubenGarcia Check out https://github.com/go-swagger/go-swagger.
This project was merged there into https://github.com/go-swagger/go-swagger/tree/master/examples/contributed-templates/stratoscale
